# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import statistics_pb2 as statistics__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in statistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStats = channel.unary_unary(
                '/StatisticsService/GetPostStats',
                request_serializer=statistics__pb2.PostIdRequest.SerializeToString,
                response_deserializer=statistics__pb2.PostStatsResponse.FromString,
                _registered_method=True)
        self.GetPostViewsDynamics = channel.unary_unary(
                '/StatisticsService/GetPostViewsDynamics',
                request_serializer=statistics__pb2.PostDynamicsRequest.SerializeToString,
                response_deserializer=statistics__pb2.DynamicsResponse.FromString,
                _registered_method=True)
        self.GetPostLikesDynamics = channel.unary_unary(
                '/StatisticsService/GetPostLikesDynamics',
                request_serializer=statistics__pb2.PostDynamicsRequest.SerializeToString,
                response_deserializer=statistics__pb2.DynamicsResponse.FromString,
                _registered_method=True)
        self.GetPostCommentsDynamics = channel.unary_unary(
                '/StatisticsService/GetPostCommentsDynamics',
                request_serializer=statistics__pb2.PostDynamicsRequest.SerializeToString,
                response_deserializer=statistics__pb2.DynamicsResponse.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/StatisticsService/GetTopPosts',
                request_serializer=statistics__pb2.TopRequest.SerializeToString,
                response_deserializer=statistics__pb2.TopPostsResponse.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/StatisticsService/GetTopUsers',
                request_serializer=statistics__pb2.TopRequest.SerializeToString,
                response_deserializer=statistics__pb2.TopUsersResponse.FromString,
                _registered_method=True)


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostViewsDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikesDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostCommentsDynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStats,
                    request_deserializer=statistics__pb2.PostIdRequest.FromString,
                    response_serializer=statistics__pb2.PostStatsResponse.SerializeToString,
            ),
            'GetPostViewsDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostViewsDynamics,
                    request_deserializer=statistics__pb2.PostDynamicsRequest.FromString,
                    response_serializer=statistics__pb2.DynamicsResponse.SerializeToString,
            ),
            'GetPostLikesDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikesDynamics,
                    request_deserializer=statistics__pb2.PostDynamicsRequest.FromString,
                    response_serializer=statistics__pb2.DynamicsResponse.SerializeToString,
            ),
            'GetPostCommentsDynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostCommentsDynamics,
                    request_deserializer=statistics__pb2.PostDynamicsRequest.FromString,
                    response_serializer=statistics__pb2.DynamicsResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=statistics__pb2.TopRequest.FromString,
                    response_serializer=statistics__pb2.TopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=statistics__pb2.TopRequest.FromString,
                    response_serializer=statistics__pb2.TopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatisticsService/GetPostStats',
            statistics__pb2.PostIdRequest.SerializeToString,
            statistics__pb2.PostStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostViewsDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatisticsService/GetPostViewsDynamics',
            statistics__pb2.PostDynamicsRequest.SerializeToString,
            statistics__pb2.DynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostLikesDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatisticsService/GetPostLikesDynamics',
            statistics__pb2.PostDynamicsRequest.SerializeToString,
            statistics__pb2.DynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostCommentsDynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatisticsService/GetPostCommentsDynamics',
            statistics__pb2.PostDynamicsRequest.SerializeToString,
            statistics__pb2.DynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatisticsService/GetTopPosts',
            statistics__pb2.TopRequest.SerializeToString,
            statistics__pb2.TopPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StatisticsService/GetTopUsers',
            statistics__pb2.TopRequest.SerializeToString,
            statistics__pb2.TopUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
