# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\" \n\rPostIdRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\"L\n\x13PostDynamicsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"C\n\x11PostStatsResponse\x12\r\n\x05views\x18\x01 \x01(\x04\x12\r\n\x05likes\x18\x02 \x01(\x04\x12\x10\n\x08\x63omments\x18\x03 \x01(\x04\"+\n\x0c\x44ynamicsItem\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04\"/\n\x10\x44ynamicsResponse\x12\x1b\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\r.DynamicsItem\"\x1c\n\nTopRequest\x12\x0e\n\x06metric\x18\x01 \x01(\t\"a\n\x10TopPostsResponse\x12%\n\x05posts\x18\x01 \x03(\x0b\x32\x16.TopPostsResponse.Item\x1a&\n\x04Item\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04\"a\n\x10TopUsersResponse\x12%\n\x05users\x18\x01 \x03(\x0b\x32\x16.TopUsersResponse.Item\x1a&\n\x04Item\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04\x32\xf7\x02\n\x11StatisticsService\x12\x34\n\x0cGetPostStats\x12\x0e.PostIdRequest\x1a\x12.PostStatsResponse\"\x00\x12\x41\n\x14GetPostViewsDynamics\x12\x14.PostDynamicsRequest\x1a\x11.DynamicsResponse\"\x00\x12\x41\n\x14GetPostLikesDynamics\x12\x14.PostDynamicsRequest\x1a\x11.DynamicsResponse\"\x00\x12\x44\n\x17GetPostCommentsDynamics\x12\x14.PostDynamicsRequest\x1a\x11.DynamicsResponse\"\x00\x12/\n\x0bGetTopPosts\x12\x0b.TopRequest\x1a\x11.TopPostsResponse\"\x00\x12/\n\x0bGetTopUsers\x12\x0b.TopRequest\x1a\x11.TopUsersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTIDREQUEST']._serialized_start=20
  _globals['_POSTIDREQUEST']._serialized_end=52
  _globals['_POSTDYNAMICSREQUEST']._serialized_start=54
  _globals['_POSTDYNAMICSREQUEST']._serialized_end=130
  _globals['_POSTSTATSRESPONSE']._serialized_start=132
  _globals['_POSTSTATSRESPONSE']._serialized_end=199
  _globals['_DYNAMICSITEM']._serialized_start=201
  _globals['_DYNAMICSITEM']._serialized_end=244
  _globals['_DYNAMICSRESPONSE']._serialized_start=246
  _globals['_DYNAMICSRESPONSE']._serialized_end=293
  _globals['_TOPREQUEST']._serialized_start=295
  _globals['_TOPREQUEST']._serialized_end=323
  _globals['_TOPPOSTSRESPONSE']._serialized_start=325
  _globals['_TOPPOSTSRESPONSE']._serialized_end=422
  _globals['_TOPPOSTSRESPONSE_ITEM']._serialized_start=384
  _globals['_TOPPOSTSRESPONSE_ITEM']._serialized_end=422
  _globals['_TOPUSERSRESPONSE']._serialized_start=424
  _globals['_TOPUSERSRESPONSE']._serialized_end=521
  _globals['_TOPUSERSRESPONSE_ITEM']._serialized_start=483
  _globals['_TOPUSERSRESPONSE_ITEM']._serialized_end=521
  _globals['_STATISTICSSERVICE']._serialized_start=524
  _globals['_STATISTICSSERVICE']._serialized_end=899
# @@protoc_insertion_point(module_scope)
